#!/bin/bash

if ! type -P git > /dev/null; then
    echo "You should install git package to use $0"
elif [ x$1 == "x" ]; then
    echo "Usage: $0 <pkgname>"
else
    git clone https://src.fedoraproject.org/rpms/$1.git fedora-$1
fi
