#!/bin/bash

if ! type -P git > /dev/null; then
    echo "You should install git package to use $0"
elif [ x$1 == "x" ]; then
    echo "Usage: $0 <pkgname>"
else
    git clone https://github.com/pld-linux/$1.git pldlinux-$1
fi
